### PR TITLE
make yesterday work for macOS

### PR DESCRIPTION
**Pull request by freemanfx**
should work for every OS since it's NodeJS

### CODE REVIEW

**Comment by mess110** [comment]
thanks for the PR, however according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth#syntax January is 0, February is 1 etc.

When testing this, this is the output I get:

```
➜  vaccinica git:(65d13dd) node scripts/yesterday.js 
6.3.2021
➜  vaccinica git:(65d13dd) date +"%d.%m.%Y" -d "yesterday"
06.04.2021
```

**Comment by mess110** [comment]
Also, please wait with fixing this, adding support for multiple months and need to take a different approach

**Comment by mess110** [comment]
@freemanfx can you please check if the new version works on macOS?

**Comment by freemanfx** [comment]
Hi. 

I had a guess that maybe the Javascript Date API will play tricks on me 😄 

I couldn't get a change to test your changes it yet, probably it works.
What I wanted to let you know is that there is REST API to discover the resources published on data.gov.ro
It uses something called CKAN:
API DOC:
https://docs.ckan.org/en/2.8/api/
And usage:
https://data.gov.ro/api/3/action/package_show?id=b86a78a3-7f88-4b53-a94f-015082592466

Thank you for your good work!

**Comment by freemanfx** [comment]
There is also an ckan client nodejs package:
https://www.npmjs.com/package/ckan

**Pull request closed without merging**
